name: Mozlang basic CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependecies
      run: |
        sudo add-apt-repository universe
        sudo add-apt-repository multiverse
        sudo apt update
        sudo apt-get install -y libgtest-dev zlib1g zlib1g-dev python3 ninja-build curl
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-18 main"
        sudo apt-get update
        sudo apt-get install -y -t llvm-toolchain-focal-18 libpolly-18-dev clang-18 llvm-18 llvm-18-dev lld-18 liblld-18-dev
    - name: Configure Cmake
      run: cmake -B build
    - name: Build
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build/test --verbose
